server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/bill-db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port-enabled: true
    non-secure-port: ${server.port}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}