server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bill-ms
          uri: lb://BILL-MS
          predicates:
            - Path=/bills/**

        - id: client-ms
          uri: lb://CLIENT-MS
          predicates:
            - Path=/clients/**

        - id: loan-ms
          uri: lb://LOAN-MS
          predicates:
            - Path=/loans/**, /devolutions/**

        - id: report-ms
          uri: lb://REPORT-MS
          predicates:
            - Path=/reports/**

        - id: tool-ms
          uri: lb://TOOL-MS
          predicates:
            - Path=/tools/**, /units/**

        - id: kardex-ms
          uri: lb://KARDEX-MS
          predicates:
            - Path=/kardex/**, /movements/**