apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-microservice-deployment
  template:
    metadata:
      labels:
        app: loan-microservice-deployment
    spec:
      containers:
        - name: loan-microservice-container
          image: locomotive1584/loan-microservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config:8888
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_LOAN
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: loan-microservice
spec:
  selector:
    app: loan-microservice-deployment
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP